### ISSUE TITLE
Queue implementation

### ISSUE THREAD

**Issue by sarat1669** [vmsgiridhar/DSA#1]
https://github.com/vmsgiridhar/DSA/blob/7fda69c364e31323d1841ec9f929ff76c6ba6824/5_Queues/Queue.py#L23

Queue can be implemented by using `Normal Linked List` as well.
We just need two linked lists

**Comment by vmsgiridhar** [comment]
A Queue can be implemented using a Normal Linked List (2 in number) - i.e., same as implementing it using 2 stacks. But, to dequeue an element, it is important for me to have a pointer to the last element, as we have a pointer to last element in doubly linked list, I could delete the last element in O(1). I guess if we are able to do this with two linked lists, then having 2 linked list, or a single doubly linked list, wouldn't make a difference. Let's see.

**Comment by sarat1669** [comment]
Yeah. I was just saying it can be done as you mentioned `We can't solve the problem using simple Linked List`.
Also, your implementation seems to be using an array instead of linked lists.

**Comment by vmsgiridhar** [comment]
Yes, we need 2 linked lists/a double linked list. Yeah, I will write the code using a Linked list soon!
